#! /usr/bin/env -S python3 -u

import sys
import re
import subprocess

from pathlib import Path
from datetime import date

MYPATH = Path(__file__).parent
ROOT = MYPATH.parent

NEW_VER = sys.argv[1]

unreleased_link_pattern = re.compile(r"^\[Unreleased\]: (.*)$", re.DOTALL)
lines = []
with open(ROOT / "CHANGELOG.md", "rt", encoding="utf-8") as change_log:
    for line in change_log.readlines():
        # Move Unreleased section to new version
        if re.fullmatch(r"^## Unreleased.*$", line, re.DOTALL):
            lines.append(line)
            lines.append("\n")
            lines.append(
                f"## [{NEW_VER}] - {date.today().isoformat()}\n"
            )
        else:
            lines.append(line)
    lines.append(f'[{NEW_VER}]: https://github.com/gershnik/wsdd-native/releases/v{NEW_VER}\n')

with open(ROOT / "CHANGELOG.md", "wt", encoding="utf-8") as change_log:
    change_log.writelines(lines)

(ROOT / "VERSION").write_text(f'{NEW_VER}\n')

readme = (ROOT / 'README.md').read_text()
readme = re.sub(r'https://github.com/gershnik/wsdd-native/releases/download/v(?:\d+(?:\.\d+)+)',
                f'https://github.com/gershnik/wsdd-native/releases/download/v{NEW_VER}',
                readme)
readme = re.sub(r'wsddn-macos-(?:\d+(?:\.\d+)+)\.pkg',
                f'wsddn-macos-{NEW_VER}.pkg',
                readme)
readme = re.sub(r'wsddn-(?:\d+(?:\.\d+)+)([-A-Za-z0-9]*)\.tgz',
                fr'wsddn-{NEW_VER}\1.tgz',
                readme)
(ROOT / 'README.md').write_text(readme)

subprocess.run(['git', 'add',
                ROOT / "README.md",
                ROOT / "CHANGELOG.md",
                ROOT / "VERSION"], check=True)
subprocess.run(['git', 'commit', '-m', f'chore: creating version {NEW_VER}'], check=True)
subprocess.run(['git', 'tag', f'v{NEW_VER}'], check=True)
