name: Check

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'SECURITY.md'
      - 'Acknowledgements.md'
      - 'config/metadata/**'
      - '.github/workflows/publish.yml'
      - '.github/workflows/build.yml'
      - 'tools/**'
  workflow_dispatch:


jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: ubuntu-22.04, compiler: gcc, version: 11 }
        - {os: ubuntu-22.04, compiler: gcc, version: 12 }
        - {os: ubuntu-22.04, compiler: gcc, version: 13 }
        - {os: ubuntu-24.04, compiler: gcc, version: 14 }
          
        - {os: ubuntu-22.04, compiler: clang, version: 13 }
        - {os: ubuntu-22.04, compiler: clang, version: 14 }
        - {os: ubuntu-22.04, compiler: clang, version: 15 }
        - {os: ubuntu-22.04, compiler: clang, version: 16 }
        - {os: ubuntu-24.04, compiler: clang, version: 17 }
        - {os: ubuntu-24.04, compiler: clang, version: 18 }
        - {os: ubuntu-24.04, compiler: clang, version: 19 }
        - {os: ubuntu-24.04, compiler: clang, version: 20 }
        - {os: ubuntu-24.04, compiler: clang, version: 21 }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

          if [[ '${{ matrix.compiler }}' == 'clang' ]]; then
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh ${{ matrix.version }}
            sudo apt-get install -y clang-tools-${{ matrix.version }} libc++-${{ matrix.version }}-dev libc++abi-${{ matrix.version }}-dev
            echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV
          fi

          if [[ '${{ matrix.compiler }}' == 'gcc' ]]; then
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}
            echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
            echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
          fi
        
      - name: Configure
        run: |
          [ -d "out" ] && tools/uncache out
          cmake -S . -B out \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: |
          installers/deb/build.py . out

  container:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix: 
        container: [gcc:15.1]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pre-requisites
      run: |
        apt-get update
        apt-get install -y ninja-build cmake
        apt-get install -y python3-dev libsystemd-dev

    - name: Configure
      shell: bash
      run: |
        [ -d "out" ] && tools/uncache out
        cmake -G Ninja -S . -B out \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Build and Test
      shell: bash
      run: |
        cmake --build out

  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
        - { os: macos-14, xcode: '15.4.0' }
        - { os: macos-15, xcode: '16.4.0' }
        - { os: macos-15-intel, xcode: '16.4.0' }
        - { os: macos-26, xcode: '26.0' }
    env: 
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure
        run: |
          [ -d "out" ] && tools/uncache out
          cmake -S . -B out \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            "-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64" \
            -DCMAKE_IGNORE_PREFIX_PATH=/opt/local \
            -DWSDDN_PREFER_SYSTEM_LIBXML2=ON

      - name: Build
        run: |
          installers/mac/build.py . out

  others:
    concurrency: ${{ matrix.remote_host }}
    runs-on: [self-hosted, server]
    strategy:
      fail-fast: false
      matrix:
        remote_host: 
          - centos-9
          - alpine-3
          - archlinux
          - netbsd-10
          - omnios
          - haiku

    steps:
      - name: Run remote build
        run: |
          "$RUNNER_TOOLS_PATH"/run-agent gh-${{ matrix.remote_host }} <<'EOF'
          set -e
          if [ ! -d work/wsdd-native ]; then
            git clone https://github.com/gershnik/wsdd-native.git work/wsdd-native
          fi
          cd work/wsdd-native
          git fetch --all
          git fetch -f --prune --tags
          git reset --hard ${{ github.sha }}
          [ -d "out" ] && tools/uncache out
          cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build out --target wsddn
          EOF
